server:
  port: 1003
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/
  instance:
    hostname: peer3
  server:
    enable-self-preservation: true