server:
  port: 1001
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:1002/eureka/,http://peer3:1003/eureka/
  instance:
    hostname: peer1
  server:
    enable-self-preservation: true