server:
  port: 1001
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    enable-self-preservation: true